### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and greatly reduce memory allocations through object pooling of SemaphoreSlim objects.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@omeryanar ?

**Comment by omeryanar** [comment]
Thanks for PR.
Can you elaborate a bit more on how AsyncKeyedLock  improves performance relative to LockProvider (which is taken from Stephen Cleary's answer in https://stackoverflow.com/questions/31138179 )?
It would be very helpful if you did a performance benchmark.

**Comment by MarkCiliaVincenti** [comment]
> Thanks for PR. Can you elaborate a bit more on how AsyncKeyedLock improves performance relative to LockProvider (which is taken from Stephen Cleary's answer in https://stackoverflow.com/questions/31138179 )? It would be very helpful if you did a performance benchmark.

Please open https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/4096117409/jobs/7063532645 and look at the results of the benchmark, ignoring the ones for NumberOfLocks=10000, Contention=10000

Compare AsyncKeyedLock to AsyncDuplicateLockFromAutoCrud (which is basically the same code you're using). You will see that your current code has up to 96% MORE allocations compared to AsyncKeyedLock. As for the performance, it varies, but they are close. The main benefit you'll get is reduced allocations.

**Comment by MarkCiliaVincenti** [comment]
Do you need anything else @omeryanar ?

**Pull request merged**
